JhulayLal Enterprise/Models/AspNetFarmer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhulayLal_Enterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetFarmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetFarmer()
        {
            this.AspNetBills = new HashSet<AspNetBill>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public string Imagepath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBill> AspNetBills { get; set; }
    }
}

JhulayLal Enterprise/Controllers/AspNetFarmersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JhulayLal_Enterprise.Models;
using System.IO;

namespace JhulayLal_Enterprise.Controllers
{
    [Authorize]
    public class AspNetFarmersController : Controller
    {
        private JhulayLalEntities db = new JhulayLalEntities();

        // GET: AspNetFarmers
        public ActionResult Index()
        {
            return View(db.AspNetFarmers.ToList());
        }

        // GET: AspNetFarmers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetFarmer aspNetFarmer = db.AspNetFarmers.Find(id);
            if (aspNetFarmer == null)
            {
                return HttpNotFound();
            }
            ViewBag.Image = aspNetFarmer.Imagepath;
            return View(aspNetFarmer);
        }

        // GET: AspNetFarmers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetFarmers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,City,Address,Contact_No,image")] Farmer etFarmer)
        {
            if (ModelState.IsValid)
            {
                AspNetFarmer obj = new AspNetFarmer();

                obj.Name = etFarmer.Name;
                obj.City = etFarmer.City;
                obj.Address = etFarmer.Address;
                obj.Contact_No = etFarmer.Contact_No;
                db.AspNetFarmers.Add(obj);
                db.SaveChanges();
                string kk = "";
                if(etFarmer.image != null)
                {
                    MemoryStream target = new MemoryStream();
                    etFarmer.image.InputStream.CopyTo(target);
                    byte[] data = target.ToArray();
                    string ImageName = System.IO.Path.GetFileName(etFarmer.image.FileName); //file2 to store path and url  
                    string physicalPath = Server.MapPath("~/Content/img/farmer/" + obj.Id);
                    if (!Directory.Exists(physicalPath))
                    {
                        Directory.CreateDirectory(physicalPath);
                    }
                    try
                    {
                        obj.Imagepath = physicalPath + "\\Pic.jpg";
                        System.IO.File.WriteAllBytes(obj.Imagepath, data);
                    }
                    catch (Exception ex)
                    {
                        if (ex.InnerException.Message == null)
                            ViewBag.error = ex.Message;
                        else
                            ViewBag.error = ex.InnerException.Message;
                    }
                    //aspomer.image.SaveAs(physicalPath);
                    kk = "/Content" + obj.Imagepath.Split(new string[] { "\\Content" }, StringSplitOptions.None)[1];
                    //obj.Imagepath = kk;
                    //etFarmer.image.SaveAs(physicalPath);
                    //obj.Imagepath = "img/" + ImageName;

                    
                }
                else
                {
                    kk = "/Content/img/user.png";
                }
                db.AspNetFarmers.Where(p => p.Id == obj.Id).FirstOrDefault().Imagepath = kk;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(etFarmer);
        }

        // GET: AspNetFarmers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetFarmer aspNetFarmer = db.AspNetFarmers.Find(id);
            if (aspNetFarmer == null)
            {
                return HttpNotFound();
            }
            return View(aspNetFarmer);
        }

        // POST: AspNetFarmers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,City,Address,Contact_No")] AspNetFarmer aspNetFarmer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetFarmer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetFarmer);
        }

        // GET: AspNetFarmers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetFarmer aspNetFarmer = db.AspNetFarmers.Find(id);
            if (aspNetFarmer == null)
            {
                return HttpNotFound();
            }
            return View(aspNetFarmer);
        }

        // POST: AspNetFarmers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AspNetFarmer aspNetFarmer = db.AspNetFarmers.Find(id);
            db.AspNetFarmers.Remove(aspNetFarmer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JhulayLal Enterprise/Views/AspNetFarmers/Create.cshtml
@model JhulayLal_Enterprise.Models.Farmer

@{
    ViewBag.Title = "Farmer";
}
<div class="box box-primary">
    @using (Html.BeginForm("Create", "AspNetFarmers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="box-header with-border">
            <h3>Add Farmer</h3>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Contact_No, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Contact_No, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Contact_No, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.image, null, new { type = "file", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                    </div>

                    @*<input id="Pic-input" type="file" style="display:block" />*@

                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JhulayLal Enterprise/Views/AspNetFarmers/Delete.cshtml
@model JhulayLal_Enterprise.Models.AspNetFarmer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetFarmer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_No)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JhulayLal Enterprise/Views/AspNetFarmers/Details.cshtml
@model JhulayLal_Enterprise.Models.AspNetFarmer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AspNetFarmer</h4>
    <hr />

    <div class="row">
        <div class="col-lg-2 col-md-offset-1">
            <img src="@ViewBag.Image" width="200" height="200" />
        </div>
        <div class="col-lg-9" style="font-size: 30px;">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Contact_No)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Contact_No)
                </dd>

            </dl>
        </div>

    </div>


    
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JhulayLal Enterprise/Views/AspNetFarmers/Edit.cshtml
@model JhulayLal_Enterprise.Models.AspNetFarmer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AspNetFarmer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JhulayLal Enterprise/Views/AspNetFarmers/Index.cshtml
@model IEnumerable<JhulayLal_Enterprise.Models.AspNetFarmer>

@{
    ViewBag.Title = "Farmers";
}

<p>
  @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-primary" })
</p>
<script>
    $(document).ready(function () {
        $('#FarmerTable').DataTable({})
    });
</script>
<div class="box box-primary">
    <div class="box-header with-border">
        <h3>Farmers List</h3>
    </div>
    <div class="box-body">
        <div style="overflow-x:auto;">
            <table id="FarmerTable" class="table table-bordered table-responsive ">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.City)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Contact_No)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Contact_No)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-primary btn-xs" }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-success btn-xs" }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-danger btn-xs" })
                            </td>
                        </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>