JhulayLal Enterprise/Models/AspNetSale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhulayLal_Enterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSale
    {
        public int Id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Particular { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Received { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Remaining { get; set; }
    
        public virtual AspNetBill AspNetBill { get; set; }
        public virtual AspNetCustomer AspNetCustomer { get; set; }
    }
}

JhulayLal Enterprise/Controllers/AspNetSalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JhulayLal_Enterprise.Models;

namespace JhulayLal_Enterprise.Controllers
{
    [Authorize]
    public class AspNetSalesController : Controller
    {
        private JhulayLalEntities db = new JhulayLalEntities();

        // GET: AspNetSales
        public ActionResult Index()
        {
            var aspNetSales = db.AspNetSales.Include(a => a.AspNetBill).Include(a => a.AspNetCustomer);
            return View(aspNetSales.ToList());
        }

        // GET: AspNetSales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetSale aspNetSale = db.AspNetSales.Find(id);
            if (aspNetSale == null)
            {
                return HttpNotFound();
            }
            return View(aspNetSale);
        }
        [HttpGet]
        public ActionResult GetRemainingBags(int Billname)
        {
            var numberofBags = db.AspNetBills.Where(x => x.Id == Billname).Select(x => x.Bags_Qty).First();
            return Json(numberofBags, JsonRequestBehavior.AllowGet);
        }

        // GET: AspNetSales/Create
        public ActionResult Create()
        {
            ViewBag.BillID = new SelectList(db.AspNetBills.Where(x => x.Bill_Status == "Not Generated"), "Id", "FarmerName");
            ViewBag.CustomerID = new SelectList(db.AspNetCustomers, "Id", "Name");
            ViewBag.Today = DateTime.Now;
            return View();
        }

        // POST: AspNetSales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
      
        public ActionResult AddSales(List<AspNetSale> aspNetSale)
        {
            try { 
                foreach(var sale in aspNetSale)
                {
                    db.AspNetSales.Add(sale);
                    AspNetBillDetail aspNetBillDetail = new AspNetBillDetail();                    
                    aspNetBillDetail.BillID = sale.BillID;
                    aspNetBillDetail.Bags = sale.Quantity;
                    aspNetBillDetail.Rate = sale.Rate;
                    aspNetBillDetail.Amount = sale.Amount;
                    db.AspNetBillDetails.Add(aspNetBillDetail);

                }
               db.SaveChanges();
            }
            catch(Exception e)
            {
                ViewBag.Error = e.Message;
            }
            return Content("1", "application/json");
            // ViewBag.BillID = new SelectList(db.AspNetBills, "Id", "Truck_No", aspNetSale.BillID);
            //ViewBag.CustomerID = new SelectList(db.AspNetCustomers, "Id", "Name", aspNetSale.CustomerID);

        }

        public ActionResult CashReceived()
        {
            ViewBag.CustomerID = new SelectList(db.AspNetCustomers, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CashReceived(AspNetSale aspNetSale)
        {
            if (ModelState.IsValid)
            {
                db.AspNetSales.Add(aspNetSale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.AspNetCustomers, "Id", "Name");
            return View(aspNetSale);
        }

        public JsonResult GetCustomerRemainings(int Id)
        {
            int? Remaining = db.AspNetSales.Where(x => x.CustomerID == Id).OrderByDescending(x => x.Id).Take(1).Select(x => x.Remaining).FirstOrDefault();
            return Json(Remaining, JsonRequestBehavior.AllowGet);
        }
        // GET: AspNetSales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetSale aspNetSale = db.AspNetSales.Find(id);
            if (aspNetSale == null)
            {
                return HttpNotFound();
            }
            ViewBag.BillID = new SelectList(db.AspNetBills, "Id", "Truck_No", aspNetSale.BillID);
            ViewBag.CustomerID = new SelectList(db.AspNetCustomers, "Id", "Name", aspNetSale.CustomerID);
            return View(aspNetSale);
        }

        // POST: AspNetSales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerID,Date,Particular,BillID,Quantity,Rate,Amount,Received,Discount,Remaining")] AspNetSale aspNetSale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetSale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillID = new SelectList(db.AspNetBills, "Id", "Truck_No", aspNetSale.BillID);
            ViewBag.CustomerID = new SelectList(db.AspNetCustomers, "Id", "Name", aspNetSale.CustomerID);
            return View(aspNetSale);
        }

        // GET: AspNetSales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetSale aspNetSale = db.AspNetSales.Find(id);
            if (aspNetSale == null)
            {
                return HttpNotFound();
            }
            return View(aspNetSale);
        }

        // POST: AspNetSales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AspNetSale aspNetSale = db.AspNetSales.Find(id);
            db.AspNetSales.Remove(aspNetSale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Sheheryer 29/12/2017
        //View TodaysSale added
        public ActionResult TodaysSale()
        {
            List<AspNetSale> todaySaleList = new List<AspNetSale>();
            todaySaleList= db.AspNetSales.Where(x => x.Date == DateTime.Today).Select(x => x).ToList();
            return View(todaySaleList);
        }
        public JsonResult FilterByDate(DateTime startDate, DateTime EndDate)
        {
            var datetoday = DateTime.Today;

            if (datetoday< startDate)
            {
                return Json("-1", JsonRequestBehavior.AllowGet);
            }
            if (datetoday < EndDate)
            {
                return Json("-1", JsonRequestBehavior.AllowGet);
            }
            if(startDate>EndDate)
            {
                return Json("-1", JsonRequestBehavior.AllowGet);
            }
            var abc = db.AspNetSales.Where(x => x.Date >= startDate && x.Date<=EndDate).GroupBy(x => x.AspNetBill.AspNetFarmer.Name).Select(x => x).ToList();
            FarmerSalesModel[] lists = new FarmerSalesModel[abc.Count];
            for (int i = 0; i < abc.Count; i++)
            {
                lists[i] = new FarmerSalesModel();
                lists[i].Name = abc[i].Key;
            }
            for (int i = 0; i < abc.Count; i++)
            {
                string name = lists[i].Name;
                var sales = db.AspNetSales.Where(sale => sale.Date >= startDate && sale.Date <= EndDate && sale.AspNetBill.AspNetFarmer.Name == name).Select(x => x).ToList();
                lists[i].saleslist = new List<Sale>();
                foreach (var item in sales)
                {
                    Sale mysale = new Sale();
                    mysale.CustomerName = item.AspNetCustomer.Name; ;
                    mysale.Particular = item.Particular;
                    mysale.Quantity = item.Quantity;
                    mysale.Rate = item.Rate;
                    mysale.Amount = item.Amount;
                    mysale.Received = item.Received;
                    mysale.Discount = item.Discount;
                    mysale.Remaining = item.Remaining;
                    mysale.truck = item.AspNetBill.Truck_No;
                    lists[i].saleslist.Add(mysale);
                }
                
            }
            return Json(lists, JsonRequestBehavior.AllowGet);
        }
        public ActionResult FarmersSale()
        {
            var abc=db.AspNetSales.GroupBy(x => x.AspNetBill.AspNetFarmer.Name).Select(x => x).ToList();
            FarmerSalesModel[] lists = new FarmerSalesModel[abc.Count];
            for (int i = 0; i < abc.Count; i++)
            {
                lists[i] = new FarmerSalesModel();
                lists[i].Name = abc[i].Key; 
            }
            for (int i = 0; i < abc.Count; i++)
            {
                string name = lists[i].Name;
                var sales = db.AspNetSales.Where(sale => sale.AspNetBill.AspNetFarmer.Name == name).Select(x => x).ToList();
                lists[i].saleslist = new List<Sale>();
                foreach (var item in sales)
                {
                    Sale mysale = new Sale();
                    mysale.CustomerName = item.AspNetCustomer.Name;
                    mysale.Particular = item.Particular;
                    mysale.Quantity = item.Quantity;
                    mysale.Rate = item.Rate;
                    mysale.Amount = item.Amount;
                    mysale.Received = item.Received;
                    mysale.Discount = item.Discount;
                    mysale.Remaining = item.Remaining;
                    mysale.truck = item.AspNetBill.Truck_No;
                    lists[i].saleslist.Add(mysale);
                }

JhulayLal Enterprise/Views/AspNetSales/CashReceived.cshtml
@model JhulayLal_Enterprise.Models.AspNetSale

@{
    ViewBag.Title = "Cash Received";
}

<script>
    $(document).ready(function () {
        $('#CustomerID').change(function ()
        {
             var id = $('#CustomerID').val();
             $.get('@Url.Action("GetCustomerRemainings","AspNetSales")',
                 { Id: id }, function (Remaining) {
                     $('#Remaining').val(parseInt(Remaining));
                     $('#hiddenRemaining').val(parseInt(Remaining));
            });
        })
        $('#Received').keyup(function () {
            var Remaining = parseInt($('#hiddenRemaining').val());
            var Received = parseInt($('#Received').val());
            console.log(Remaining + "  " + Received);
            if (!isNaN(Received))
            {
                $('#Remaining').val(Remaining - Received);
            }
           
        });
    });
</script>
<div class="box box-primary">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="box-header with-border">
        <h3>Cash Received</h3>
    </div>
    <div class="box-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Particular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Particular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Particular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Received, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Received, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Received, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Remaining, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remaining, new { htmlAttributes = new { @class = "form-control" } })
                    <div hidden>
                        @Html.EditorFor(model => model.Remaining, new { htmlAttributes = new { @class = "form-control", @id = "hiddenRemaining" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.Remaining, "", new { @class = "text-danger" })
                </div>
            </div>

           
        </div>
    </div>
    <div class="box-footer">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Cash" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JhulayLal Enterprise/Views/AspNetSales/Create.cshtml
@model JhulayLal_Enterprise.Models.AspNetSale

@{
    ViewBag.Title = "Sales";
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script>
    var AspNetSale =
        {
            CustomerID: '',
            Date: '',
            Particular: '',
            BillID: '',
            Quantity: '',
            Rate: '',
            Amount: '',
            Received: '',
            Discount: '',
            Remaining:''
        }
    var RemainingBalance = 0;
    $(document).ready(function () {


        $('#CustomerID').change(function () {
            var id = $('#CustomerID').val();
             $.get('@Url.Action("GetCustomerInfomration","AspNetCustomers")',
                 { Id: id }, function (data) {
                     RemainingBalance = data.Remaining;
            });
        });
        $("#AddBags").bind("click", function () {

            $("#BagsTableBody").append(GetEnrollmentRow(-1));
            $('#BagsTable tr:last td:first').append($("#BillID").clone());
            $('#BagsTable tr:last #Quantity').change(function () {
                ChangeQuantity(this);
            });
            $('#BagsTable tr:last #Rate').keyup(function () {
                ChangeRate(this);
            });
            $('#BagsTable tr:last #Received').keyup(function () {
                ChangeReceived(this);
            });
            $('#BagsTable tr:last #Discount').keyup(function () {
                ChangeDiscount(this);
            });
            $('#BagsTable tr:last #Bill').change(function (e) {                
                var r  = $('#BillID')[0].value
                ChangeRemainingBags(this,r);
            });
            $('#BagsTable tr:last #Amount').change(function () {
                CalculateRemaining(this);
            });

            var a = $('#BillID')[0].value
            ChangeRemainingBags(this, a);
        });

        $("#AddSale").bind("click", function () {
            aspNetSale = [];

            $("#BagsTableBody tr").each(function () {
                AspNetSale = Object.create(AspNetSale);
                AspNetSale.CustomerID = $("#CustomerID").val();
                AspNetSale.Date = $("#Date").val();
                AspNetSale.BillID = $(this).find('#BillID').val();
                AspNetSale.Discount = $(this).find('#Discount').val();
                AspNetSale.Particular = $(this).find('#Particular').val();
                AspNetSale.Quantity = $(this).find('#Quantity').val();
                AspNetSale.Rate = $(this).find("#Rate").val();
                AspNetSale.Amount = $(this).find("#Amount").val();
                AspNetSale.Received = $(this).find("#Received").val();
                AspNetSale.Remaining = $(this).find("#Remaining").val();
                aspNetSale.push(AspNetSale);
                console.log(AspNetSale);
            });

            var aspNetSale = JSON.stringify(aspNetSale);
            $.ajax({
                contentType: 'application/json; charset=utf-8',
                dataType:'json',
                type:'POST',
                url:'/AspNetSales/AddSales',
                data: "{aspNetSale:" + aspNetSale+"}",
                success:function(flag)
                {
                    if(flag==1)
                    {
                        location.href='@Url.Action("Index", "AspNetSales")';
                    }
                }
            });

        });
    });

    function ChangeQuantity(Quantity) {
        tr = Quantity.closest("tr");
        var Rate = parseInt($("input[id='Rate']", tr).val());
        var QuantityVal = parseInt($(Quantity).val());
        var Amount = 0;
        if (!isNaN(Rate) && !isNaN(QuantityVal)) {
            Amount = parseInt(Rate * QuantityVal);
        }

        $("input[id='Amount']", tr).val(Amount);

        CalculateRemaining();
    }

    function ChangeRate(Rate) {
        tr = Rate.closest("tr");
        var Quantity = parseInt($("input[id='Quantity']", tr).val());
        var RateVal = parseInt($(Rate).val());
        var Amount = 0;
        if (!isNaN(Quantity) && !isNaN(RateVal)) {
            Amount = parseInt(Quantity * RateVal);
        }
        $("input[id='Amount']", tr).val(Amount);
        CalculateRemaining();

    }
    function ChangeReceived(Received) {
        tr = Received.closest("tr");
        var Remaining = parseInt($("input[id='Remaining']", tr).val());
        var Received = parseInt($(Received).val());
        CalculateRemaining();

    }
    function ChangeDiscount(Discount) {
        tr = Discount.closest("tr");
        var Remaining = parseInt($("input[id='Remaining']", tr).val());
        var Discount = parseInt($(Discount).val());
        CalculateRemaining();

    }
    function ChangeRemainingBags(td,Select)
    {
        tr = td.closest('tr');
        $.get('@Url.Action("GetRemainingBags","AspNetSales")',
        { Billname: Select }, function (data) {
            $("td[id='RemainingBags']", tr).html(parseInt(data));
        });
    }
    function CalculateRemaining()
    {
        TempRemaining = RemainingBalance;
        console.log("Temp Remaining:"+TempRemaining);
        $("#BagsTableBody tr").each(function () {

            var Amount = parseInt($(this).find('#Amount').val());
            var Discount = parseInt( $(this).find('#Discount').val());
            var Received = parseInt($(this).find('#Received').val());

            if (isNaN(Amount))
            {
                Amount = 0;
            }
            if (isNaN(Discount)) {
                Discount = 0;
            }
            if (isNaN(Received)) {
                Received = 0;
            }

            TempRemaining = (((TempRemaining + Amount) - Discount) - Received);
            console.log("Temp Remaining After Sub:" + TempRemaining);
            $("input[id='Remaining']", $(this)).val(TempRemaining);

        });
    }


    function DeleteRow(btndel) {
        if (typeof (btndel) == "object") {
            $(btndel).closest("tr").remove();
        }
        else {
            return false;
        }
    }

    function GetEnrollmentRow(value) {

        var html = ' <tr><td id="Bill"></td><td><select id="Particular" class="form-control"><option value="Sale">Sale</option><option value="Cash">Cash</option></select></td><td id="RemainingBags"></td><td><input id="Quantity" class="form-control"></td><td><input id="Rate" class="form-control"></td><td><input id="Amount" class="form-control"></td><td><input id="Received" class="form-control"></td><td><input id="Discount" class="form-control"></td><td><input id="Remaining" value=' + RemainingBalance + ' class="form-control"></td><td><input type="button" class="btn btn-danger remove" value="Remove" onclick="DeleteRow(this);"></td></tr>';
        return html;
    }
</script>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3>Add New Sales</h3>
    </div>
    <div class="box-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" ,@type="date"} })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

    </div>
    <div class="box-footer">
        <button id="AddBags" class="btn btn-primary">Add Bags</button>
    </div>
</div>

<div class="box box-primary">
    <div class="box-header with-border">
        <center><h3 class="box-title">Sales Detail</h3></center>
    </div>
    <div class="box-body">
        <div style="overflow-x:auto;">
            <table id="BagsTable" class="table table-striped table-responsive table-hover table-bordered ">
                <thead>
                    <tr>
                        <th>
                            Farmer Name
                        </th>
                        <th>
                            Particular
                        </th>
                        <th>
                            Total Bags
                        </th>
                        <th>
                            No. of Bags
                        </th>
                        <th>
                            Rate/Piece
                        </th>
                        <th>
                            Amount
                        </th>
                        <th>
                            Received
                        </th>
                        <th>
                            Discount
                        </th>
                        <th>
                            Remaining
                        </th>
                    </tr>
                </thead>
                <tbody id="BagsTableBody"></tbody>
            </table>
        </div>
    </div>
    <div class="box-footer">
                <input id="AddSale" type="submit" value="Add Sales" class="btn btn-primary" />

    </div>
</div>
<div hidden>
    <div class="form-group">
        @Html.LabelFor(model => model.BillID, "BillID", htmlAttributes: new { @class = "control-label col-md-2", @name = "BillID[]" })
        <div class="col-md-10">
            @Html.DropDownList("BillID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BillID, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JhulayLal Enterprise/Views/AspNetSales/Delete.cshtml
@model JhulayLal_Enterprise.Models.AspNetSale

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetSale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Particular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Particular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Received)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Received)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remaining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remaining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetBill.Truck_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetBill.Truck_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetCustomer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetCustomer.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JhulayLal Enterprise/Views/AspNetSales/Details.cshtml
@model JhulayLal_Enterprise.Models.AspNetSale

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AspNetSale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Particular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Particular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Received)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Received)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remaining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remaining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetBill.Truck_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetBill.Truck_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetCustomer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetCustomer.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>