JhulayLal Enterprise/Models/AspNetCustomer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhulayLal_Enterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetCustomer()
        {
            this.AspNetSales = new HashSet<AspNetSale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public byte[] Picture { get; set; }
        public string Imagepath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetSale> AspNetSales { get; set; }
    }
}

JhulayLal Enterprise/Controllers/AspNetCustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JhulayLal_Enterprise.Models;
using System.IO;

namespace JhulayLal_Enterprise.Controllers
{
    [Authorize]
    public class AspNetCustomersController : Controller
    {
        private JhulayLalEntities db = new JhulayLalEntities();

        // GET: AspNetCustomers
        public ActionResult Index()
        {
            return View(db.AspNetCustomers.ToList());
        }

        // GET: AspNetCustomers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetCustomer aspNetCustomer = db.AspNetCustomers.Find(id);
            List<AspNetSale> aspNetSales = db.AspNetSales.Where(x => x.CustomerID == id).ToList();
            ViewBag.Name = aspNetCustomer.Name;
            ViewBag.ContactNo = aspNetCustomer.Contact_No;
            ViewBag.AccountNo = aspNetCustomer.AccountNo;
            ViewBag.Image = aspNetCustomer.Imagepath;
            ViewBag.CNIC = aspNetCustomer.CNIC;
            if (aspNetCustomer == null)
            {
                return HttpNotFound();
            }
            return View(aspNetSales);
        }

        // GET: AspNetCustomers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetCustomers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,City,Address,Contact_No,CNIC,AccountNo,Picture")] AspNetCustomer aspNetCustomer)
        {
            if (ModelState.IsValid)
            {

                db.AspNetCustomers.Add(aspNetCustomer);

                db.SaveChanges();
                int cutomerID = db.AspNetCustomers.Max(x => x.Id);
                AspNetSale aspNetSale = new AspNetSale();
                aspNetSale.Particular = "Opening Balance";
                aspNetSale.Date = DateTime.Now;
                aspNetSale.Remaining = Convert.ToInt32(Request.Form["OpeningBalance"]);
                aspNetSale.CustomerID = cutomerID;
                db.AspNetSales.Add(aspNetSale);
                return RedirectToAction("Index");
            }

            return View(aspNetCustomer);
        }


        public ActionResult Creaoote([Bind(Include = "Id,Name,City,Address,Contact_No,CNIC,AccountNo,Picture,image")] Customer aspomer)
        {
            if (ModelState.IsValid)
            {
                AspNetCustomer obj = new AspNetCustomer();

                obj.AccountNo = aspomer.AccountNo;
                obj.Address = aspomer.Address;
                obj.City = aspomer.City;
                obj.CNIC = aspomer.CNIC;
                obj.Contact_No = aspomer.Contact_No;
                obj.Name = aspomer.Name;

                db.AspNetCustomers.Add(obj);
                db.SaveChanges();
                string kk = "";
                if(aspomer.image != null)
                {
                    MemoryStream target = new MemoryStream();
                    aspomer.image.InputStream.CopyTo(target);
                    byte[] data = target.ToArray();

                    string ImageName = System.IO.Path.GetFileName(aspomer.image.FileName); //file2 to store path and url  
                    string physicalPath = Server.MapPath("~/Content/img/customer/" + obj.Id);
                    if (!Directory.Exists(physicalPath))
                    {
                        Directory.CreateDirectory(physicalPath);
                    }
                    try
                    {
                        obj.Imagepath = physicalPath + "\\Pic.jpg";
                        System.IO.File.WriteAllBytes(obj.Imagepath, data);
                    }
                    catch (Exception ex)
                    {
                        if (ex.InnerException.Message == null)
                        {
                            ViewBag.error = ex.Message;
                        }
                        else
                            ViewBag.error = ex.InnerException.Message;
                    }
                    //aspomer.image.SaveAs(physicalPath);
                    kk = "/Content" + obj.Imagepath.Split(new string[] { "\\Content" }, StringSplitOptions.None)[1];
                    

                }
                else
                {
                    kk = "/Content/img/user.png";
                }
                db.AspNetCustomers.Where(p => p.Id == obj.Id).FirstOrDefault().Imagepath = kk;
                db.SaveChanges();



                //obj.Picture = BinaryReader.ReadBytes(dd);
                //byte[] image = BinaryReader.ReadBytes(108732);

                //db.AspNetCustomers.Add(aspNetCustomer);

                //db.SaveChanges();
                int cutomerID = db.AspNetCustomers.Max(x => x.Id);
                AspNetSale aspNetSale = new AspNetSale();
                aspNetSale.Particular = "Opening Balance";
                aspNetSale.Date = DateTime.Now;
                aspNetSale.Remaining = Convert.ToInt32(Request.Form["OpeningBalance"]);
                aspNetSale.CustomerID = cutomerID;
                db.AspNetSales.Add(aspNetSale);
                return RedirectToAction("Index");
            }

            return View(aspomer);
        }

        // GET: AspNetCustomers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetCustomer aspNetCustomer = db.AspNetCustomers.Find(id);
            if (aspNetCustomer == null)
            {
                return HttpNotFound();
            }
            return View(aspNetCustomer);
        }

        // POST: AspNetCustomers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,City,Address,Contact_No,CNIC,AccountNo,Picture")] AspNetCustomer aspNetCustomer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetCustomer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetCustomer);
        }

        // GET: AspNetCustomers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetCustomer aspNetCustomer = db.AspNetCustomers.Find(id);
            if (aspNetCustomer == null)
            {
                return HttpNotFound();
            }
            return View(aspNetCustomer);
        }

        // POST: AspNetCustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AspNetCustomer aspNetCustomer = db.AspNetCustomers.Find(id);
            db.AspNetCustomers.Remove(aspNetCustomer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class CustomerInformation
        {
            public AspNetCustomer aspNetCustomer { get; set; }
            public int? Remaining { get; set; }
        }
        public JsonResult GetCustomerInfomration(int Id)
        {
            AspNetCustomer aspNetCustomer = db.AspNetCustomers.Find(Id);
            int? Remaining = db.AspNetSales.Where(x => x.CustomerID == Id).OrderByDescending(x => x.Id).Take(1).Select(x => x.Remaining).FirstOrDefault() ;
            CustomerInformation customerInformation = new CustomerInformation();
            customerInformation.aspNetCustomer = new AspNetCustomer();
            customerInformation.aspNetCustomer.Name = aspNetCustomer.Name;
            customerInformation.aspNetCustomer.Contact_No = aspNetCustomer.Contact_No;
            customerInformation.aspNetCustomer.CNIC = aspNetCustomer.CNIC;
            customerInformation.aspNetCustomer.AccountNo = aspNetCustomer.AccountNo;

            customerInformation.Remaining = Remaining;
            return Json(customerInformation, JsonRequestBehavior.AllowGet);
        }

        
    }
}

JhulayLal Enterprise/Views/AspNetCustomers/Create.cshtml
@model JhulayLal_Enterprise.Models.Customer

@{
    ViewBag.Title = "Farmer";
}
<div class="box box-primary">
    @using (Html.BeginForm("Creaoote", "AspNetCustomers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="box-header with-border">
            <h3>Add Customer</h3>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Contact_No, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Contact_No, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Contact_No, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CNIC, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CNIC, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CNIC, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccountNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Picture, new { htmlAttributes = new {type = "file", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Opening Balance</label>

                    <div class="col-md-10">
                        <input class="form-control" type="text" id="OpeningBalance" name="OpeningBalance" />

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.image, null, new { type = "file", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                    </div>
                    
                    @*<input id="Pic-input" type="file" style="display:block" />*@

                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JhulayLal Enterprise/Views/AspNetCustomers/Delete.cshtml
@model JhulayLal_Enterprise.Models.AspNetCustomer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetCustomer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JhulayLal Enterprise/Views/AspNetCustomers/Details.cshtml
@model IEnumerable<JhulayLal_Enterprise.Models.AspNetSale>

@{
    ViewBag.Title = "Customer";
}

<script>
    $(document).ready(function () {
        $('#CustomerDetail').DataTable({
        })
    });
</script>


<div class="box box-primary">
    <div class="box-header with-border">
        <h3>Customer Details</h3>
    </div>
    <div class="box-header with-border">

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">
                        <img src="@ViewBag.Image" width="200" height="200" />
                    </div>
                    <div class="col-md-5">
                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <td>
                                        <b>Customer Name:</b>
                                    </td>
                                    <td>
                                        @ViewBag.Name
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Contact No:</b>
                                    </td>
                                    <td>
                                        @ViewBag.ContactNo
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Account No:</b>
                                    </td>
                                    <td>
                                        @ViewBag.AccountNo
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>CNIC No:</b>
                                    </td>
                                    <td>
                                        @ViewBag.CNIC
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
    <div class="box-body">
        <table id="CustomerDetail" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Particular)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Quantity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Rate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Received)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Discount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Remaining)
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Particular)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Rate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Received)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Discount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Remaining)
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

JhulayLal Enterprise/Views/AspNetCustomers/Edit.cshtml
@model JhulayLal_Enterprise.Models.AspNetCustomer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AspNetCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CNIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CNIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JhulayLal Enterprise/Views/AspNetCustomers/Index.cshtml
@model IEnumerable<JhulayLal_Enterprise.Models.AspNetCustomer>

@{
    ViewBag.Title = "Customers";
}

<p>
  @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-primary" })
</p>
<script>
    $(document).ready(function () {
        $('#CustomerTable').DataTable({ })
    });
</script>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3>Customers List</h3>
    </div>
    <div class="box-body">
        <div style="overflow-x:auto;">
            <table id="CustomerTable" class="table table-responsive  table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.City)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Contact_No)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CNIC)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AccountNo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Picture)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Contact_No)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CNIC)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AccountNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Picture)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-primary btn-xs" }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-success btn-xs" }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-danger btn-xs" })
                            </td>
                        </tr>
                }

                </tbody>
            </table>
        </div>
    </div>
</div>